### ISSUE TITLE
Image alternative text

### ISSUE THREAD

**Issue by ghost** [h5o/h5o-chrome#21]
Hi,

Thanks for making this real useful tool.
In my opinion, the outline tool shouldn't ignore alternative text values for images.

An example:
`<h1><img alt="Company name" src="company-logo.svg"></h1>`

Currently, the outliner tool will not include the company name as a header.

Cheers! Bob

**Comment by dominykas** [comment]
There's a PR waiting for this: https://github.com/h5o/h5o-js/pull/34

I will try to get back to it soon.
