### ISSUE TITLE
Bug when open pop-up

### ISSUE THREAD

**Issue by niklissad** [h5o/h5o-chrome#22]
Hello

I have bug when open pop-up

Maybe you can fix it with css
```
html, body {
  height: 100%
}
```

![screen shot 2017-01-13 at 11 36 10 am](https://cloud.githubusercontent.com/assets/6731591/21925091/88099c0e-d984-11e6-8129-1de56a57454a.png)

**Comment by dominykas** [comment]
This is a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=457887

Also a duplicate here: #9
