### ISSUE TITLE
Please add support for file:// protocol as well

### ISSUE THREAD

**Issue by ahmadalfy** [h5o/h5o-chrome#24]

**Comment by dominykas** [comment]
No, sorry, I won't publish that in Chrome Store.

You can install the `crx` directly - it has the support: https://github.com/h5o/h5o-chrome/releases

**Comment by ahmadalfy** [comment]
Just out of curiosity, why you don't want to add this feature? It's not harmful as far as I know and I see a lot of extensions allow it.

Thanks for the link, unfortunately I am using multiple machines with different operating systems. I will have to install it manually on every machine I run.

**Comment by dominykas** [comment]
Mostly because early on when I started building this, I did not ask for that permission in the manifest - and I don't want all the users to have to re-grant all the permissions, esp. with one that might be as "scary" as "local file access". There are a lot of malicious extensions (and evil people looking to buy them) out there.

**Comment by ahmadalfy** [comment]
Thanks for the feedback, but are you sure about the permission? Extensions does not work on file protocol unless you explicitly tell them to. So by default the users won't get that notification (or at least I think so)

![screenshot_1](https://cloud.githubusercontent.com/assets/87611/25652714/dd42be92-2fe9-11e7-86b1-88d788d40eff.png)

Thank you so much again for taking time to explain. I am just asking if you have time to check if the permission point is going to ask for permissions then ignore it. If not; please consider adding the feature.

Thanks

**Comment by dominykas** [comment]
I've no idea how Chrome will react and I've no way to test it without publishing to the Chrome Store... if you can figure it out and point me to documentation/official responses - I'm happy to reconsider.
