### ISSUE TITLE
Click on outline entry jumps to index.html

### ISSUE THREAD

**Issue by ahartman** [h5o/h5o-chrome#31]
Click on an outline element in HTML5 outliner dropdown and HTML5 outliner jumps to index.html; it does not find the element on the current page.

= A click works well on index.html: the topic is found and blinks a few times.
= However, on other pages than index.html, Outliner jumps to index.html when clicking.
= Please observe two attached screen images. The first one - at 09 07 43 - shows page offer.html and Outliner, with the correct outline. The second screen image - at 09 07 49 - shows the result after clicking on a line in Outliner on offer.html. Outliner has jumped from offer.html to index.html.

Chrome, Versie 64.0.3282.186 on Mac
Extension 0.8.13

Regards, André Hartman, Belgium

<img width="2048" alt="schermafbeelding 2018-03-14 om 09 07 43" src="https://user-images.githubusercontent.com/688316/37390197-6d146adc-2767-11e8-89b0-8ca2a83533e1.png">
<img width="2048" alt="schermafbeelding 2018-03-14 om 09 07 49" src="https://user-images.githubusercontent.com/688316/37390200-71857098-2767-11e8-89f7-e0e4796ce851.png">

**Comment by dominykas** [comment]
It shows the same headings on both screenshots. Are you using frames/iframes?

**Comment by ahartman** [comment]
Dear dominykas,
This is exactly what happens. Click on an outline on offer.html and index.html appears although the outline is still of offer.html. It looks as if Outliner looks for the clicked topic on index.html and not on offer.html. This is a completely static web site, a project of my son for his IT classes. No iframes.

I took out the images and zipped the code, please find attached.
Regards, André Hartman
[Test2.zip](https://github.com/h5o/h5o-chrome/files/1810249/Test2.zip)

**Comment by dominykas** [comment]
Sorry, there must be something happening in Chrome or smth - outliner just tries to read the contents of the active page and I'm not sure why it would treat the active page as active. I'm unable to reproduce on other pages, so your best bet is to fire up developer tools and try to debug what's going on.
