### ISSUE TITLE
Have short height diabox in Chrome - MacOS

### ISSUE THREAD

**Issue by monamedia** [h5o/h5o-chrome#32]
I have no issue with my Windows PC but usually got this trouple when using on my Mac. 

Rightnow my solutions is just close tab and open and try 
![screen shot 2018-03-16 at 02 05 12](https://user-images.githubusercontent.com/6325729/37485650-a89399a4-28be-11e8-9ace-2ffd15c3515e.png)

**Comment by dominykas** [comment]
Duplicate #9
