### ISSUE TITLE
Is there a way to omit everything that is "Untitled"?

### ISSUE THREAD

**Issue by reddioment** [h5o/h5o-chrome#33]
There are some sites that have a bunch of untitled SECTION, NAV and ASIDE. These are usually just paragraphs under a heading. Is there a way to omit these so that they don't get listed?
Here is an example [screenshot](https://ibb.co/m5QiUn) from this [website](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Initialization.html).

**Comment by dominykas** [comment]
No. This would also be against the standard. `section` should not be used just for the sake of it - it's not a `div`, it has a meaning. `nav` and `aside` are slightly different, but they are defined as sectioning routes and so they create implied headers.
