### ISSUE TITLE
<footer> Tag

### ISSUE THREAD

**Issue by antoniolvlindo** [h5o/h5o-chrome#43]
I encountered an issue with the footer tag during a project. While intended to be a child element of the body, the footer content wasn't displaying properly. Interestingly, replacing the footer tag with a section tag resolved the problem.

![image](https://github.com/h5o/h5o-chrome/assets/104741336/2894f149-e562-4ea2-bc58-4e4c5d0fb654)

**Comment by dominykas** [comment]
![Screenshot 2024-02-06 at 13 49 52](https://github.com/h5o/h5o-chrome/assets/505619/df5e549b-51fb-494e-87fc-063d689b3d03)

Not sure how the issue is relevant here.
