### ISSUE TITLE
Article without section

### ISSUE THREAD

**Issue by pall-dinamiza** [h5o/h5o-chrome#7]
The following html:

```
    <body>
        <h1>First level</h1>
        <h2>Second level</h2>
        <article>
            <h3>Third level</h3>
        </article>
    </body>
```

results in:

```
    1. First level
        1. Second level
        2. Third level
```

instead of:

```
    1. First level
        1. Second level
            1. Third level
```

while with a section like this:

```
    <body>
        <h1>First level</h1>
        <section>
            <h2>Second level</h2>
            <article>
                <h3>Third level</h3>
            </article>
        </section>
    </body>
```

or without any sectioning:

```
    <body>
        <h1>First level</h1>
        <h2>Second level</h2>
        <h3>Third level</h3>
    </body>
```

outputs it correctly.

**Comment by dominykas** [comment]
This is correct behaviour as that is how it is specified in the HTML5 outlining algorithm.

The `h2` creates an implied section, so your first example is equivalent to this:

```
  <body>
        <h1>First level</h1>
        <section>
            <h2>Second level</h2>
        </section>
        <article>
            <h3>Third level</h3>
        </article>
    </body>
```

The heading "number" inside the sectioning content does not matter per se - in your first example, the `h3` is the heading for the `article`. If you had it as `h2` or `h1` or even `h6`, without other headings, you'd get the same outline. The `article` is at the same level as the implied section of the `h2`, therefore its heading also has the same rank - and that is why you end up with the outline like you do.

**Comment by dominykas** [comment]
Honestly, my recommendation would be to do exactly what you did with your last two examples - either ALWAYS use sectioning elements, or NEVER use them.

**Comment by pall-dinamiza** [comment]
The implied section of a header should contain every content until the next header of equal or higher level. Thus it should look like this:

```
    <body>
        <h1>First level</h1>
        <section>
            <h2>Second level</h2>
            <article>
                <h3>Third level</h3>
            </article>
        </section>
    </body>
```

otherwise the following html:

```
    <body>
        <h1>First level</h1>
        <h2>Second level</h2>
        <h3>Third level</h3>
    </body>
```

would result in:

```
    <body>
        <section>
            <h1>First level</h1>
        </section>
        <section>
            <h2>Second level</h2>
        </section>
        <section>
            <h3>Third level</h3>
        </section>
    </body>
```

as well as the following html:

```
    <body>
        <h1>First level</h1>
        <section>
            <h2>Second level</h2>
            <article>
                <h3>Third level</h3>
            </article>
        </section>
    </body>
```

would result in:

```
    <body>
        <section>
            <h1>First level</h1>
        </section>
        <section>
            <section>
                <h2>Second level</h2>
            </section>
            <article>
                <h3>Third level</h3>
            </article>
        </section>
    </body>
```

implied sections, not to mention the fact that there can be multiple h1  on the same level, as well as headers do not necesserly have to be the first element of a section, so no, this isn't the correct behaviour!

**Comment by pall-dinamiza** [comment]
"The article is at the same level as the implied section of the h2, therefore its heading also has the same rank - and that is why you end up with the outline like you do." 

This is WRONG, if an sectioning element is on the same level of a header it's own header is one level under.

**Comment by dominykas** [comment]
Here's what the specification says:

> Sectioning content elements are always considered subsections of their nearest ancestor sectioning root or their nearest ancestor element of sectioning content, whichever is nearest, regardless of what implied sections other headings may have created.

So, in your original example:

```
    <body>
        <h1>First level</h1>
        <h2>Second level</h2>
        <article>
            <h3>Third level</h3>
        </article>
    </body>
```

The `article` is a sectioning content element, and it is a subsection of `body`. The `h1` is the heading for the `body` (spec: "The first element of heading content in an element of sectioning content represents the heading for that section."), and both - the `h2` and the `article` are subsections of that.

**Comment by dominykas** [comment]
Do note, that in your other examples you're incorrectly assuming, that an `h1`-`h6` _always_ creates a new implied section. It does not. It only creates an implied section, if the current section already has a heading.

**Comment by dominykas** [comment]
In fact, your example is actually almost the same as the very first example under "Headings and sections" in the specification:
- W3C: http://www.w3.org/TR/html5/sections.html#headings-and-sections
- WHATWG: https://html.spec.whatwg.org/multipage/semantics.html#headings-and-sections

**Comment by pall-dinamiza** [comment]
My bad, skipped that line in the specs. Indeed the specs are quite clear about it, altough IMHO this breaks the backward compatibility of the document outline. Anyway thanks for pointing me to the right direction.
