### ISSUE TITLE
can't install the HTML5 Outliner from Webstore

### ISSUE THREAD

**Issue by oksymets** [h5o/h5o-chrome#8]
It says that the app is downloading already, but when I click "reload" in the dialogue window  the page reloads, but nothing happens

**Comment by dominykas** [comment]
I'm sorry, I'm unable to reproduce this, and I was able to install succesfully, without any trouble, on latest version on Chrome.

Although I think this is likely a problem with Chrome or Chrome store itself, maybe even temporary, could you provide some screenshots?

In the meantime, I'm closing this.

**Comment by oksymets** [comment]
I thought my Chrome was up-to-date, but it wasn't. Now everything is OK)
